spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
  data:
    rest:
      base-path: "api"
security:
  ignored:
    - "/contacts/*"
    - "/api/*"
