spring:
  datasource:
    username:
    password:
    url:
    continue-on-error: true
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
         current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext