spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
  data:
    rest:
      base-path: "api"
security:
  ignored:
    - "/contacts/*"
    - "/api/*"
app:
  name: PhoneBook

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: springboot
